import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent { label 'master' }
  environment {
    appName = "variable" 
  }
  stages {
    stage("Stage: Pruebas funcionales API "){ 
      steps {
          script {			
           bat "echo 'hola mundo'"
        }
      }
    }
    stage("Stage: Pruebas CdA de QA"){ 
      steps {
          script {			
           bat "echo 'hola mundo'"
        }
      }
    }
    stage("Stage: Pruebas CdA de Seguridad"){ 
      steps {
          script {			
           bat "echo 'hola mundo'"
        }
      }
    }
  }
  post {
      always {          
//          deleteDir()
           bat "echo 'fase always'"
      }
      success {
            bat "echo 'fase success'"
        }

      failure {
            bat "echo 'fase failure'"
      }
      
  }
}  
